### ISSUE TITLE
Unable to run container

### ISSUE THREAD

**Issue by BlackSwiftSoftware** [digitalpardoe/docker-rmlint#1]
I'm new to docker, so forgive any dumb questions. However, I think there's a bug or an issue with the docker image for rmlint. I've spent the better part of a couple of days trying to get things to work and reading up on rmlint and docker.

I have a couple of issues. First and foremost, I cannot get the container to run using your CLI instructions. Here are my steps:

I created the docker image on the Synology NAS by downloading it from the registry and using your CLI instructions.

When I create the container, with something like:

`docker create -v /volume1/dup-test/ -v /volume1/rmlint-output/ --name rmlint digitalpardoe/rmlint`

It seems to work and the container gets created. (I can see the container inside the docker app in the Synology.)

BUT running

`docker run -it rmlint /bin/bash`

Doesn't work and gives the error:

> Unable to find image 'rmlint:latest' locally
> docker: Error response from daemon: repository rmlint not found: does not exist or no pull access.
> See 'docker run --help'

Likewise, I get the same error message if I try to run the container using the hash I'm given after creating it instead of the name, e.g.

`docker run -it c0a5c64c3b4071371643e2ca2ea42e1008a1a651fbeac709ce4708adceb0ab3e /bin/bash
`

Now, if I go into the Synology through the web interface and try to run the container, it immediately crashes and quits. This makes me think something's wrong with the container or how it's setup.

But, if I create the container through the Docker app on the Synology (instead of the command line), I am then able to run the container without it crashing. I can even change the containers settings to mount directories at given paths.

I can use the already running container via terminal like so:

`docker exec -it rmlint bash`

But then I notice that it's running an old version of rmlint, version 2.6.1. And from what I understand, to get the latest version, the image needs to be updated in the registry? I'd really like to have the latest version (2.9.0) to use features described in the documentation of rmlint.

So, the two questions/issues are:

1. Why is the container not running via your command line instructions? Why does the container crash and quit? Is this a bug or configuration problem?
2. Is there a way to get the latest version of rmlint into the image myself? Can I update the image somehow? Or is that something you do to update the image? (And if so, can you update it?)

I had really hoped to get rmlint running on the Synology itself with docker instead of using the Mac's terminal to talk to the NAS, but man, it's been a struggle.

Thanks so much.

**Comment by mindrunner** [comment]
I am not related to this repository (which seems stale and unmaintained)

Answering your questions:

1) The instructions are misleading. `docker create` does not start a container. It creates one.
2) I created a fork, using the most recent ubuntu image and a docker auto-build.

https://github.com/mindrunner/docker-rmlint

Feel free to use that one instead. Also, I am happy to merge any changes regarding the documentation if you feel like updating it.

Not sure if `2.8.0` helps or do you really need `2.9.0`?

```
sh-4.3# docker run -ti runmymind/docker-rmlint rmlint --version                                                              
version 2.8.0 compiled: Jan 28 2019 at [00:31:11] "Maidenly Moose" (rev 3)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.
sh-4.3# 
```


Cheers
Lukas

**Comment by digitalpardoe** [comment]
Hi @BlackSwiftSoftware, apologies for taking until now to notice your message - this `rmlint` image isn't one I come back to often hence it spends most of its time abandoned.

I've now updated the image and the README, thanks @mindrunner for paving over my negligence towards this repository.

**Comment by BlackSwiftSoftware** [comment]
Thanks @digitalpardoe! I'll play around with it when I get the chance.
